name: Build and Push Docker image

on:
  push:
    branches: [minor, ci-arch-build-test]
    tags:
      - 'v*' # Push events to version tags like v1.2.3

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/beammp-server

jobs:
  build-and-push:
    #runs-on: debian-12
    runs-on: [self-hosted, x64]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: setup-buildx

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta_full
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            # always tag sha value
            type=raw,value=${{ github.sha }}
            # For  to the develop branch, tag as 'nightly'
            type=raw,value=nightly,enable=${{ github.ref == 'refs/heads/ci-arch-build-test' }}
            # For pushes of v* tags, create 'latest' and version tags (e.g., v1.2.3)
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
      - name: Extract metadata for slim image
        id: meta_slim
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            # always tag sha value
            type=raw,value=${{ github.sha }}-slim
            # For pushes to the develop branch, tag as 'nightly-slim'
            type=raw,value=nightly-slim,enable=${{ github.ref == 'refs/heads/ci-arch-build-test' }}
            # For pushes of v* tags, create 'slim' and version-slim tags (e.g., v1.2.3-slim)
            type=raw,value=slim,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{version}},suffix=-slim,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
      - name: Get vcpkg hash
        id: vcpkg_hash
        run: echo "hash=$(git rev-parse HEAD:vcpkg)" >> $GITHUB_OUTPUT
      - name: Cache vcpkg_installed
        uses: actions/cache@v4
        id: cache
        with:
          path: vcpkg_installed_cache
          key: ${{ runner.os }}-vcpkg-installed-cache-${{ hashFiles('vcpkg.json') }}-${{ steps.vcpkg_hash.outputs.hash }}
      - name: Restore Docker cache mounts
        uses: reproducible-containers/buildkit-cache-dance@v3
        with:
          builder: ${{ steps.setup-buildx.outputs.name }}
          cache-dir: vcpkg_installed_cache
          dockerfile: Dockerfile
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}
      - name: Build and push Docker image
        id: build_and_push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          load: true
          tags: ${{ steps.meta_full.outputs.tags }}
          labels: ${{ steps.meta_full.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Tag built image for slimming
        run: |
          set -ex
          IMG=${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker pull "$IMG"
          docker tag "$IMG" slim:from
      - name: Set up slim image
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: slim:from
          tag: to
      - name: Tag and push slim images
        run: |
          set -ex
          tags="${{ steps.meta_slim.outputs.tags }}"
          echo "The following slim tags will be pushed: ${{ steps.meta_slim.outputs.tags }}"
          while IFS= read -r tag; do
            echo "Tagging and pushing: ${tag}"
            docker tag slim:to "${tag}"
            docker push "${tag}"
          done <<< "$tags"
