name: Linux

on:
  push:
    branches:
      - 'develop'
      - 'minor'
      - 'ci-arch-build-test'
  pull_request:

env: 
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_FORCE_SYSTEM_BINARIES: 1
  CMAKE_BUILD_TYPE: "Release"
  DEBIAN_FRONTEND: "noninteractive"

jobs:
  x86_64-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: debian
            version: 11
          - distro: debian
            version: 12
          - distro: ubuntu
            version: 22.04
          - distro: ubuntu
            version: 24.04
          - distro: archlinux
            version: latest
    container:
      image: ${{ matrix.distro }}:${{ matrix.version }}
    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Install git
        run: (apt update -yq && apt install -yq git) || pacman -Syq --noconfirm git

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        run: bash ./scripts/${{ matrix.distro }}-${{ matrix.version }}/1-install-deps.sh

      - name: Git config safe directory
        run: bash ./scripts/${{ matrix.distro }}-${{ matrix.version }}/1.5-git-safe.sh

      - name: get-cmake
        uses: lukka/get-cmake@v4.0.3

      - name: Get vcpkg hash
        id: vcpkg_hash
        run: echo "hash=$(git rev-parse HEAD:vcpkg)" >> $GITHUB_OUTPUT

      - name: Cache vcpkg packages
        uses: actions/cache@v4
        with:
          path: bin/vcpkg_installed
          key: vcpkg-${{ matrix.distro }}-${{ matrix.version }}-x86_64-${{ hashFiles('vcpkg.json') }}-${{ steps.vcpkg_hash.outputs.hash }}
          restore-keys: |
            vcpkg-${{ matrix.distro }}-${{ matrix.version }}-x86_64-

      - name: Create Build Environment
        run: bash ./scripts/${{ matrix.distro }}-${{ matrix.version }}/2-configure.sh '-DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake'

      - name: Build Server
        run: bash ./scripts/${{ matrix.distro }}-${{ matrix.version }}/3-build.sh

      - name: Archive server artifact
        uses: actions/upload-artifact@v4
        with:
          name: BeamMP-Server.${{ matrix.distro }}.${{ matrix.version }}.x86_64
          path: ./bin/BeamMP-Server

      - name: Archive server debug info artifact
        uses: actions/upload-artifact@v4
        with:
          name: debuginfo.${{ matrix.distro }}.${{ matrix.version }}.x86_64
          path: ./bin/BeamMP-Server.debug

      - name: Build Tests
        run: bash ./scripts/${{ matrix.distro }}-${{ matrix.version }}/3-build-tests.sh

      - name: Install Runtime Dependencies
        run: bash ./scripts/${{ matrix.distro }}-${{ matrix.version }}/4-install-runtime-deps.sh

      - name: Test
        run: ./bin/BeamMP-Server-tests

  arm64-matrix:
    runs-on: ubuntu-22.04-arm
    env:
      VCPKG_DEFAULT_TRIPLET: "arm64-linux"
    strategy:
      matrix:
        include:
          - distro: debian
            version: 11
          - distro: debian
            version: 12
          - distro: ubuntu
            version: 22.04
          - distro: ubuntu
            version: 24.04
    container:
      image: ${{ matrix.distro }}:${{ matrix.version }}
    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Install git
        run: (apt update -yq && apt install -yq git) || pacman -Syq --noconfirm git

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        run: bash ./scripts/${{ matrix.distro }}-${{ matrix.version }}/1-install-deps.sh

      - name: Git config safe directory
        run: bash ./scripts/${{ matrix.distro }}-${{ matrix.version }}/1.5-git-safe.sh

      - name: get-cmake
        uses: lukka/get-cmake@v4.0.3

      - name: Cache vcpkg packages
        uses: actions/cache@v4
        with:
          path: bin/vcpkg_installed
          key: vcpkg-${{ matrix.distro }}-${{ matrix.version }}-arm64-${{ hashFiles('vcpkg.json') }}-$(git rev-parse --short HEAD:vcpkg)
          restore-keys: |
            vcpkg-${{ matrix.distro }}-${{ matrix.version }}-arm64-

      - name: Create Build Environment
        run: bash ./scripts/${{ matrix.distro }}-${{ matrix.version }}/2-configure.sh '-DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake'

      - name: Build Server
        run: bash ./scripts/${{ matrix.distro }}-${{ matrix.version }}/3-build.sh

      - name: Archive server artifact
        uses: actions/upload-artifact@v4
        with:
          name: BeamMP-Server.${{ matrix.distro }}.${{ matrix.version }}.arm64
          path: ./bin/BeamMP-Server

      - name: Archive server debug info artifact
        uses: actions/upload-artifact@v4
        with:
          name: debuginfo.${{ matrix.distro }}.${{ matrix.version }}.arm64
          path: ./bin/BeamMP-Server.debug

      - name: Build Tests
        run: bash ./scripts/${{ matrix.distro }}-${{ matrix.version }}/3-build-tests.sh

      - name: Install Runtime Dependencies
        run: bash ./scripts/${{ matrix.distro }}-${{ matrix.version }}/4-install-runtime-deps.sh

      - name: Test
        run: ./bin/BeamMP-Server-tests
